name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions

on:

  push:

  workflow_dispatch:

jobs:

  Explore-GitHub-Actions:

    runs-on: ubuntu-latest

    steps:

      - run: |
           echo "secret ${{ secrets.MY }} ."
           echo "variable ${{ vars.JOB_NAME }} ."

